EccomerceWeb/EccomerceWeb/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccomerceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}

EccomerceWeb/EccomerceWeb/Controllers/ProductController.cs
using EccomerceWeb.DataAccess;
using EccomerceWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EccomerceWeb.Controllers
{
    public class ProductController : Controller
    {

        //TrendUpProductDbContext db = new TrendUpProductDbContext();
        TrendUpEntities db = new TrendUpEntities();
        // GET: Product
        public ActionResult Index()
        {
            return View(db.Products.ToList());

        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                   
                    db.Products.Add(product);
                    db.SaveChanges();
                    
                    return RedirectToAction("Index");

                }
                return View(product);
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);

        }
    }
}

EccomerceWeb/EccomerceWeb/Controllers/ShoppingCartController.cs
using EccomerceWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EccomerceWeb.Controllers
{
    public class ShoppingCartController : Controller
    {
        TrendUpEntities db = new TrendUpEntities();
        private const string strCart = "Cart";
        // GET: ShoppingCart
        public ActionResult Index()
        { 
            return View();
        }
        public ActionResult OrderNow(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (Session[strCart] == null)
            {
                List<Cart> lsCart = new List<Cart> {
                new Cart(db.Products.Find(id),1)
                };
                Session[strCart] = lsCart;
            }
            else
            {
                List<Cart> lsCart = (List<Cart>)Session[strCart];
                int check = isExistingCheck(id);
                if (check == -1)
                    lsCart.Add(new Cart(db.Products.Find(id), 1));
                else
                    lsCart[check].Quantity++;
                Session[strCart] = lsCart;

            }
            return View("Index");
        }

        private int isExistingCheck(int? id)
        {
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < lsCart.Count; i++)
            {
                if (lsCart[i].Product.ProductID == id) { return i; }
            }
            return -1;
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int check = isExistingCheck(id);
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            lsCart.RemoveAt(check);
            return View("Index");
        }
        public ActionResult UpdateCart(FormCollection frc)
        {
            string[] quantities = frc.GetValues("quantity");
            var lstCart = (List<Cart>)Session[strCart];
            for (int i = 0;i < lstCart.Count; i++)
            {
                lstCart[i].Quantity = Convert.ToInt32(quantities[i]);

            }
            Session[strCart] = lstCart;
            return View("Index");
        }
        public ActionResult CheckOut()
        {
           
            return View("CheckOut");
        }
        public ActionResult ProcessOrder(FormCollection frc)
        {
            List<Cart> lstCart = (List<Cart>)Session[strCart];
            Order order = new Order()
            {
                UserFname = frc["fname"],
                UserLname = frc["lname"],
                UserPhone = frc["number"],
                UserEmail = frc["compemailany"],
                OrderDate = DateTime.Now,
                Address = frc["add1"],
                City = frc["city"],
                State = frc["state"],
                Zip = frc["zip"],
            };
           
            decimal total = 0;
            foreach(Cart cart in lstCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderID = order.OrderID,
                    ProductID = cart.Product.ProductID,
                    Quantity = cart.Quantity,
                    Price = cart.Product.Price
                };
                total += System.Convert.ToDecimal(orderDetail.Quantity * orderDetail.Price);
                db.OrderDetails.Add(orderDetail);
            }
            order.TotalPrice = total;
            db.Orders.Add(order);
            db.SaveChanges();


            // Remove all shopping cart session
            Session.Remove(strCart);
            return View("OrderSuccess");
        }


    }
}

EccomerceWeb/EccomerceWeb/Views/Product/Create.cshtml
@model EccomerceWeb.Models.Product

@{
    ViewBag.Title = "Create";
}

<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Add Product</h2>

            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->

<div id="contact-container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn_3 button-contactForm btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>

EccomerceWeb/EccomerceWeb/Views/Product/Details.cshtml
@model EccomerceWeb.Models.Product
@{
    ViewBag.Title = "ProductDetails";
}


<!--================Single Product Area =================-->
<div class="product_image_area section_padding">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-5">
                <div class="product_slider_img">
                    <div id="vertical">
                        <div data-thumb="@Model.ImagePath">
                            <img src="@Model.ImagePath" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>@Model.Name</h3>
                    <h2>$@Math.Round(Model.Price, 2)</h2>
                    <ul class="list">
                        <li>
                            <a class="active" href="#">
                                <span>Category</span> : Household
                            </a>
                        </li>
                        <li>
                            <a href="#"> <span>Availibility</span> : In Stock</a>
                        </li>
                    </ul>
                    <p>
                        @Model.Description
                    </p>
                    <div class="card_area">
                        <div class="product_count d-inline-block">
                            <span class="inumber-decrement"> <i class="ti-minus"></i></span>
                            <input class="input-number" type="text" value="1" min="0" max="10">
                            <span class="number-increment"> <i class="ti-plus"></i></span>
                        </div>
                        <div class="add_to_cart">
                            <a href="@Url.Action("OrderNow","ShoppingCart", new { id = Model.ProductID }, null)" class="btn_3">add to cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EccomerceWeb/EccomerceWeb/Views/Product/Index.cshtml
@model IEnumerable<EccomerceWeb.Models.Product>

@{
    ViewBag.Title = "ProductIndex";
}


<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Our Shop</h2>

            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->


<section class="cat_product_area section_padding border_top">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="left_sidebar_area">
                    <aside class="left_widgets p_filter_widgets sidebar_box_shadow">
                        <div class="l_w_title">
                            <h3>Browse Categories</h3>
                        </div>
                        <div class="widgets_inner">
                            <ul class="list">
                                <li>
                                    <a href="#">Accessories</a>
                                </li>
                                <li class="sub-menu">
                                    <a href="#Electronics" class=" d-flex justify-content-between">
                                        Home Decoration
                                        <div class="right ti-plus"></div>
                                    </a>
                                    <ul>
                                        <li>
                                            <a href="#">Wallpaper</a>
                                        </li>
                                        <li>
                                            <a href="#">Bedding</a>
                                        </li>
                                        <li>
                                            <a href="#">Office</a>
                                        </li>
                                        <li>
                                            <a href="#">Furniture</a>
                                        </li>
                                        <li>
                                            <a href="#">Plants</a>
                                        </li>
                                        
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Traveling</a>
                                </li>
                                <li>
                                    <a href="#">Sports</a>
                                </li>
                                <li>
                                    <a href="#">Handmade products</a>
                                </li>
                            </ul>
                        </div>
                    </aside>

                    <aside class="left_widgets p_filter_widgets sidebar_box_shadow">
                        <div class="l_w_title">
                            <h3>Product filters</h3>
                        </div>
                        <div class="widgets_inner">
                            <ul class="list">
                                <p>Categorized by Feel</p>
                                <li>
                                    <input type="radio" aria-label="Radio button for following text input">
                                    <a href="#">Modern</a>
                                </li>
                                <li>
                                    <input type="radio" aria-label="Radio button for following text input">
                                    <a href="#">Vintage</a>
                                </li>
                                <li class="active">
                                    <input type="radio" aria-label="Radio button for following text input">
                                    <a href="#">Classic</a>
                                </li>
                                <li>
                                    <input type="radio" aria-label="Radio button for following text input">
                                    <a href="#">Retro</a>
                                </li>
                                <li>
                                    <input type="radio" aria-label="Radio button for following text input">
                                    <a href="#">Pop</a>
                                </li>
                            </ul>
                            
                        </div>
                    </aside>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product_top_bar d-flex justify-content-between align-items-center">
                            <div class="single_product_menu product_bar_item">
                                <h2>Womans (12)</h2>
                            </div>
                            <div class="product_top_bar_iner product_bar_item d-flex">
                                <div class="product_bar_single">
                                    <select class="wide">
                                        <option data-display="Default sorting">Default sorting</option>
                                        <option value="1">Price High to Low</option>
                                        <option value="2">Price Low to High</option>
                                    </select>
                                </div>
                                <div class="product_bar_single">
                                    <select>
                                        <option data-display="Show 12">Show 12</option>
                                        <option value="1">Show 20</option>
                                        <option value="2">Show 30</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    @foreach (var product in Model)
                    {
                    <div class="col-lg-4 col-sm-6">
                        <div class="single_category_product">
                            <div class="single_category_img">
                                <a href="@Url.Action("Details", "Product", new { id = product.ProductID }, null)">
                                    <img src="@product.ImagePath" alt=""></a>

                                    <div class="category_product_text">
                                        <a href="@Url.Action("Details", "Product", new { id = product.ProductID }, null)"><h5>@product.Name</h5></a>
                                        <p>$@Math.Round(product.Price, 2)</p>
                                        <a href="@Url.Action("OrderNow","ShoppingCart", new { id = product.ProductID }, null)" class="btn_1">Add to cart</a>
                                    </div>
</div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>